Add enemy randomization
CCDirectLink/CCItemRandomizer pull request #1
Opened 2023-07-22 18:30 UTC by krypciak

2023-07-23 15:59 UTC, krypciak commented
Ready for merge

2023-07-24 11:24 UTC, 2767mr requested changes
Found some crashes by looking for `DO_ENEMY_ACTION` in `assets/data/maps`

2023-07-24 11:24 UTC, 2767mr commented on enemy-data.json
> +        "mine-diggingbot": { "elements": [0, 0, 0, 0], "mapElements": "", "endurance": 6 },
Crashes in `cold-dng.b1.control-a`

2023-07-24 11:24 UTC, 2767mr commented on enemy-data.json
> +        "forest.bug-samurai-shock": { "elements": [0, 0, 0, 0], "mapElements": "", "endurance": 2.5 },
Crashes in `forest.path-09` though technically not in logic

2023-07-24 11:24 UTC, 2767mr commented on enemy-data.json
> +        "heat.heat-golem": { "elements": [0, 1, 0, 0], "mapElements": "waterBubblePanel", "endurance": 6 },
Crashes in `heat-dng.f3.room-04`

2023-07-24 11:26 UTC, krypciak commented
Can you provide your seed/randomizerState.json?

2023-07-24 11:27 UTC, 2767mr commented
Almost all seed will crash but here is one example: `4_6073387360149325`

2023-07-24 11:31 UTC, krypciak commented
I cannot reproduce your crashing issues, but I've run into an infinite cutscene at `heat-dng.f3.room-04`
Are you on the latest commit?

2023-07-24 11:35 UTC, 2767mr commented
I thought I was but I was on the wrong repo. I can see the same infinite loop

2023-07-24 11:39 UTC, 2767mr commented
Btw, you should use an editor with TS support. If you already have that do `npx tsc --init`, add `"noImplicitAny": false,` to the tsconfig and then do `npx tsc` to check for errors

2023-07-24 11:44 UTC, krypciak commented
I use neovim and I have error checking, Are there any errors in my code?

2023-07-24 11:47 UTC, 2767mr commented
<img width="702" alt="image" src="https://github.com/CCDirectLink/CCItemRandomizer/assets/2082553/21e39d80-416e-46a5-b11d-b23ba3f0c375">

2023-07-24 12:31 UTC, krypciak commented
Should be fixed

2023-07-24 21:05 UTC, 2767mr approved these changes

2023-07-24 21:05 UTC, merged